In [1]:
# Import dependencies
import pandas as pd

In [2]:
# Open the file
tourney_csv = "MNCAATourneyDetailedResults.csv"
tourney_df = pd.read_csv(tourney_csv)

tourney_df.head()

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
0,2003,134,1421,92,1411,84,N,1,32,69,...,31,14,31,17,28,16,15,5,0,22
1,2003,136,1112,80,1436,51,N,0,31,66,...,16,7,7,8,26,12,17,10,3,15
2,2003,136,1113,84,1272,71,N,0,31,59,...,28,14,21,20,22,11,12,2,5,18
3,2003,136,1141,79,1166,73,N,0,29,53,...,17,12,17,14,17,20,21,6,6,21
4,2003,136,1143,76,1301,74,N,1,27,64,...,21,15,20,10,26,16,14,5,8,19

In [3]:
# Add a column of W for winner
tourney_df['OutcomeW'] = 'W'

tourney_df.head()

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF,OutcomeW
0,2003,134,1421,92,1411,84,N,1,32,69,...,14,31,17,28,16,15,5,0,22,W
1,2003,136,1112,80,1436,51,N,0,31,66,...,7,7,8,26,12,17,10,3,15,W
2,2003,136,1113,84,1272,71,N,0,31,59,...,14,21,20,22,11,12,2,5,18,W
3,2003,136,1141,79,1166,73,N,0,29,53,...,12,17,14,17,20,21,6,6,21,W
4,2003,136,1143,76,1301,74,N,1,27,64,...,15,20,10,26,16,14,5,8,19,W

In [4]:
# Add a column of L for loser
tourney_df['OutcomeL'] = 'L'

tourney_df.head()

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF,OutcomeW,OutcomeL
0,2003,134,1421,92,1411,84,N,1,32,69,...,31,17,28,16,15,5,0,22,W,L
1,2003,136,1112,80,1436,51,N,0,31,66,...,7,8,26,12,17,10,3,15,W,L
2,2003,136,1113,84,1272,71,N,0,31,59,...,21,20,22,11,12,2,5,18,W,L
3,2003,136,1141,79,1166,73,N,0,29,53,...,17,14,17,20,21,6,6,21,W,L
4,2003,136,1143,76,1301,74,N,1,27,64,...,20,10,26,16,14,5,8,19,W,L

In [5]:
# Stack winning and losing results using concatenate
results_df = pd.concat([
        tourney_df[['Season','DayNum','WTeamID','WScore','OutcomeW','NumOT','WFGM','WFGA','WFGM3','WFGA3','WFTM','WFTA','WOR','WDR','WAst','WTO','WStl','WBlk','WPF']].rename(columns={
            'WTeamID':'TeamID', 'WScore':'Score','OutcomeW':'Outcome','WFGM':'FGM','WFGA':'FGA','WFGM3':'FGM3', 'WFGA3':'FGA3','WFTM':'FTM','WFTA':'FTA','WOR':'OR','WDR':'DR','WAst':'Ast','WTO':'TO','WStl':'Stl','WBlk':'Blk','WPF':'PF'}),
        tourney_df[['Season','DayNum','LTeamID','LScore','OutcomeL','NumOT','LFGM','LFGA','LFGM3','LFGA3','LFTM','LFTA','LOR','LDR','LAst','LTO','LStl','LBlk','LPF']].rename(columns={
            'LTeamID':'TeamID', 'LScore':'Score','OutcomeL':'Outcome','LFGM':'FGM','LFGA':'FGA','LFGM3':'FGM3','LFGA3':'FGA3','LFTM':'FTM','LFTA':'FTA','LOR':'OR','LDR':'DR','LAst':'Ast','LTO':'TO','LStl':'Stl','LBlk':'Blk','LPF':'PF'})
])

# View df
results_df.head(50)

,Season,DayNum,TeamID,Score,Outcome,NumOT,FGM,FGA,FGM3,FGA3,FTM,FTA,OR,DR,Ast,TO,Stl,Blk,PF
0,2003,134,1421,92,W,1,32,69,11,29,17,26,14,30,17,12,5,3,22
1,2003,136,1112,80,W,0,31,66,7,23,11,14,11,36,22,16,10,7,8
2,2003,136,1113,84,W,0,31,59,6,14,16,22,10,27,18,9,7,4,19
3,2003,136,1141,79,W,0,29,53,3,7,18,25,11,20,15,18,13,1,19
4,2003,136,1143,76,W,1,27,64,7,20,15,23,18,20,17,13,8,2,14
5,2003,136,1163,58,W,0,17,52,4,14,20,27,12,29,8,14,3,8,16
6,2003,136,1181,67,W,0,19,54,4,13,25,31,13,27,4,16,10,8,23
7,2003,136,1211,74,W,0,20,47,6,14,28,37,8,28,12,12,2,2,15
8,2003,136,1228,65,W,0,24,56,5,14,12,14,15,23,15,14,11,4,14
9,2003,136,1242,64,W,0,28,51,2,6,6,11,7,20,13,11,8,4,17
10,2003,136,1266,72,W,0,22,51,9,16,19,23,11,20,14,10,4,3,23
11,2003,136,1281,72,W,0,28,52,5,13,11,18,9,32,7,23,4,6,19
12,2003,136,1323,70,W,0,23,54,3,13,21,25,11,33,7,20,6,6,19
13,2003,136,1328,71,W,0,24,52,10,18,13,24,11,24,16,14,8,3,12
14,2003,136,1390,77,W,0,29,64,8,24,11,15,12,29,16,14,4,8,24
15,2003,136,1409,84,W,0,33,57,8,12,10,13,8,26,18,12,6,1,11
16,2003,136,1458,81,W,0,31,58,6,16,13,22,10,24,16,9,7,2,16
17,2003,137,1120,65,W,1,25,57,7,18,8,13,14,24,11,15,4,5,16
18,2003,137,1139,47,W,0,18,47,5,18,6,8,7,19,5,8,3,0,15
19,2003,137,1196,85,W,0,32,61,13,28,8,14,9,31,24,10,6,3,15
20,2003,137,1231,67,W,0,19,49,7,18,22,26,13,22,15,8,1,2,17
21,2003,137,1246,95,W,0,40,65,10,20,5,11,10,25,22,13,7,4,17
22,2003,137,1257,86,W,0,35,70,8,24,8,13,15,29,18,12,12,4,22
23,2003,137,1268,75,W,0,27,54,10,19,11,15,8,27,17,13,3,3,20
24,2003,137,1277,79,W,0,26,56,7,13,20,25,10,28,16,11,5,1,18
25,2003,137,1329,77,W,0,27,50,7,20,16,28,10,15,15,11,12,0,17
26,2003,137,1338,87,W,0,33,59,9,16,12,21,10,23,22,9,14,6,19
27,2003,137,1345,80,W,0,27,52,9,16,17,19,8,25,7,19,9,1,18
28,2003,137,1393,76,W,0,30,52,4,11,12,15,11,28,16,18,5,9,17
29,2003,137,1400,82,W,0,31,62,6,16,14,20,19,28,15,14,6,2,16
30,2003,137,1428,60,W,0,18,61,9,23,15,18,13,23,8,15,7,4,22
31,2003,137,1448,76,W,0,29,69,6,23,12,20,19,29,13,19,8,9,19
32,2003,137,1462,71,W,0,26,64,6,20,13,18,17,30,19,10,5,4,11
33,2003,138,1112,96,W,2,34,74,7,24,21,29,18,29,18,9,7,4,20
34,2003,138,1163,85,W,0,31,68,6,10,17,21,17,26,12,9,4,1,13
35,2003,138,1181,86,W,0,32,52,10,15,12,16,4,23,14,11,15,9,18
36,2003,138,1242,108,W,0,40,59,5,9,23,34,12,28,21,13,6,6,20
37,2003,138,1266,101,W,1,35,62,12,18,19,20,8,25,18,12,6,0,20
38,2003,138,1323,68,W,0,25,61,13,24,5,5,5,32,12,11,5,4,13
39,2003,138,1328,74,W,0,26,51,7,13,15,24,13,23,16,12,2,2,15
40,2003,138,1458,61,W,0,22,57,6,22,11,17,10,22,12,5,5,3,11
41,2003,139,1120,68,W,0,24,56,4,19,16,20,12,21,11,14,9,6,18
42,2003,139,1139,79,W,0,27,52,14,22,11,19,10,18,21,12,6,2,11
43,2003,139,1246,74,W,0,26,55,4,13,18,18,13,22,11,13,4,3,16
44,2003,139,1268,77,W,0,30,58,3,13,14,17,7,32,19,8,2,6,21
45,2003,139,1277,68,W,0,25,45,6,16,12,18,9,21,15,10,5,0,18
46,2003,139,1338,74,W,0,25,47,4,9,20,28,10,21,15,11,9,1,14
47,2003,139,1393,68,W,0,26,57,5,12,11,18,5,33,16,17,11,9,19
48,2003,139,1400,77,W,0,25,62,5,11,22,26,13,27,8,13,4,0,21
49,2003,143,1112,88,W,0,36,76,7,14,9,11,14,30,19,10,12,5,17

In [6]:
# Import reg season results to make one df of all game records
# Open the file
reg_season_csv = "MRegularSeasonDetailedResults.csv"
reg_season_df = pd.read_csv(reg_season_csv)

reg_season_df.head()

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFGA3,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF
0,2003,10,1104,68,1328,62,N,0,27,58,...,10,16,22,10,22,8,18,9,2,20
1,2003,10,1272,70,1393,63,N,0,26,62,...,24,9,20,20,25,7,12,8,6,16
2,2003,11,1266,73,1437,61,N,0,24,58,...,26,14,23,31,22,9,12,2,5,23
3,2003,11,1296,56,1457,50,N,0,18,38,...,22,8,15,17,20,9,19,4,3,23
4,2003,11,1400,77,1208,71,N,0,30,61,...,16,17,27,21,15,12,10,7,1,14

In [7]:
# Add a column of W for winner
reg_season_df['OutcomeW'] = 'W'

reg_season_df.head()

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFTM,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF,OutcomeW
0,2003,10,1104,68,1328,62,N,0,27,58,...,16,22,10,22,8,18,9,2,20,W
1,2003,10,1272,70,1393,63,N,0,26,62,...,9,20,20,25,7,12,8,6,16,W
2,2003,11,1266,73,1437,61,N,0,24,58,...,14,23,31,22,9,12,2,5,23,W
3,2003,11,1296,56,1457,50,N,0,18,38,...,8,15,17,20,9,19,4,3,23,W
4,2003,11,1400,77,1208,71,N,0,30,61,...,17,27,21,15,12,10,7,1,14,W

In [8]:
# Add a column of L for loser
reg_season_df['OutcomeL'] = 'L'

reg_season_df.head()

,Season,DayNum,WTeamID,WScore,LTeamID,LScore,WLoc,NumOT,WFGM,WFGA,...,LFTA,LOR,LDR,LAst,LTO,LStl,LBlk,LPF,OutcomeW,OutcomeL
0,2003,10,1104,68,1328,62,N,0,27,58,...,22,10,22,8,18,9,2,20,W,L
1,2003,10,1272,70,1393,63,N,0,26,62,...,20,20,25,7,12,8,6,16,W,L
2,2003,11,1266,73,1437,61,N,0,24,58,...,23,31,22,9,12,2,5,23,W,L
3,2003,11,1296,56,1457,50,N,0,18,38,...,15,17,20,9,19,4,3,23,W,L
4,2003,11,1400,77,1208,71,N,0,30,61,...,27,21,15,12,10,7,1,14,W,L

In [9]:
# Stack winning and losing results using concatenate
season_results_df = pd.concat([
        reg_season_df[['Season','DayNum','WTeamID','WScore','OutcomeW','NumOT','WFGM','WFGA','WFGM3','WFGA3','WFTM','WFTA','WOR','WDR','WAst','WTO','WStl','WBlk','WPF']].rename(columns={
            'WTeamID':'TeamID', 'WScore':'Score','OutcomeW':'Outcome','WFGM':'FGM','WFGA':'FGA','WFGM3':'FGM3', 'WFGA3':'FGA3','WFTM':'FTM','WFTA':'FTA','WOR':'OR','WDR':'DR','WAst':'Ast','WTO':'TO','WStl':'Stl','WBlk':'Blk','WPF':'PF'}),
        reg_season_df[['Season','DayNum','LTeamID','LScore','OutcomeL','NumOT','LFGM','LFGA','LFGM3','LFGA3','LFTM','LFTA','LOR','LDR','LAst','LTO','LStl','LBlk','LPF']].rename(columns={
            'LTeamID':'TeamID', 'LScore':'Score','OutcomeL':'Outcome','LFGM':'FGM','LFGA':'FGA','LFGM3':'FGM3','LFGA3':'FGA3','LFTM':'FTM','LFTA':'FTA','LOR':'OR','LDR':'DR','LAst':'Ast','LTO':'TO','LStl':'Stl','LBlk':'Blk','LPF':'PF'})
])

# View df
season_results_df.head(50)

,Season,DayNum,TeamID,Score,Outcome,NumOT,FGM,FGA,FGM3,FGA3,FTM,FTA,OR,DR,Ast,TO,Stl,Blk,PF
0,2003,10,1104,68,W,0,27,58,3,14,11,18,14,24,13,23,7,1,22
1,2003,10,1272,70,W,0,26,62,8,20,10,19,15,28,16,13,4,4,18
2,2003,11,1266,73,W,0,24,58,8,18,17,29,17,26,15,10,5,2,25
3,2003,11,1296,56,W,0,18,38,3,9,17,31,6,19,11,12,14,2,18
4,2003,11,1400,77,W,0,30,61,6,14,11,13,17,22,12,14,4,4,20
5,2003,11,1458,81,W,0,26,57,6,12,23,27,12,24,12,9,9,3,18
6,2003,12,1161,80,W,0,23,55,2,8,32,39,13,18,14,17,11,1,25
7,2003,12,1186,75,W,0,28,62,4,14,15,21,13,35,19,19,7,2,21
8,2003,12,1194,71,W,0,28,58,5,11,10,18,9,22,9,17,9,2,23
9,2003,12,1458,84,W,0,32,67,5,17,15,19,14,22,11,6,12,0,13
10,2003,13,1166,106,W,0,41,69,15,25,9,13,15,29,21,11,10,6,16
11,2003,13,1202,74,W,0,29,51,7,13,9,11,6,21,18,15,7,1,5
12,2003,13,1237,66,W,0,26,66,5,19,9,13,21,23,15,17,12,3,17
13,2003,13,1323,76,W,0,25,56,10,23,16,23,8,35,18,13,14,19,13
14,2003,14,1125,83,W,1,30,70,11,31,12,15,15,18,22,16,18,5,21
15,2003,14,1156,78,W,0,27,46,10,18,14,24,8,25,18,15,2,6,18
16,2003,14,1161,81,W,0,22,48,5,12,32,43,16,32,13,24,5,3,19
17,2003,14,1166,82,W,0,33,61,8,19,8,14,9,23,21,17,14,5,18
18,2003,14,1183,73,W,0,29,59,9,19,6,8,8,21,17,15,10,1,19
19,2003,14,1314,85,W,0,32,60,5,15,16,23,12,34,18,14,8,4,12
20,2003,14,1323,89,W,0,34,62,8,16,13,21,12,34,25,11,9,13,16
21,2003,14,1353,60,W,0,23,57,4,19,10,15,15,18,10,12,14,6,18
22,2003,14,1390,61,W,0,20,53,6,27,15,24,15,24,9,14,4,2,17
23,2003,14,1426,59,W,0,25,53,1,5,8,12,15,32,14,16,6,4,7
24,2003,14,1462,87,W,0,35,70,6,19,11,16,17,27,18,7,13,3,10
25,2003,15,1161,77,W,0,27,58,5,10,18,27,18,26,15,12,5,4,21
26,2003,15,1194,93,W,2,33,75,9,20,18,33,17,26,14,14,17,0,21
27,2003,15,1196,76,W,0,28,48,4,13,16,24,8,23,18,18,13,5,19
28,2003,15,1242,81,W,0,28,53,3,5,22,37,13,29,12,19,10,3,21
29,2003,15,1422,84,W,0,33,53,3,8,15,20,7,36,12,22,5,9,19
30,2003,16,1314,71,W,0,27,57,5,14,12,19,14,30,19,20,8,5,13
31,2003,16,1390,63,W,0,23,57,6,15,11,21,17,20,12,10,8,1,19
32,2003,17,1196,99,W,0,39,73,11,28,10,22,16,31,32,14,10,14,19
33,2003,17,1304,68,W,0,27,58,6,18,8,13,10,28,13,17,5,5,26
34,2003,18,1104,82,W,0,24,49,10,20,24,34,12,26,13,13,7,3,14
35,2003,18,1113,59,W,0,22,54,1,12,14,25,13,27,12,15,6,5,15
36,2003,18,1116,81,W,0,25,65,4,18,27,48,29,48,12,27,11,8,29
37,2003,18,1117,83,W,0,30,72,7,19,16,20,24,17,12,12,8,3,14
38,2003,18,1120,81,W,0,32,54,3,11,14,23,9,27,14,19,13,9,15
39,2003,18,1122,81,W,1,29,70,11,24,12,17,13,27,19,13,6,5,27
40,2003,18,1123,72,W,0,24,52,7,19,17,22,11,21,11,14,2,3,16
41,2003,18,1133,95,W,1,34,79,5,24,22,34,19,40,17,15,7,1,21
42,2003,18,1139,69,W,0,27,53,10,24,5,9,4,22,22,12,7,0,18
43,2003,18,1140,71,W,0,21,49,8,13,21,27,10,25,12,17,6,1,25
44,2003,18,1141,61,W,0,21,50,2,12,17,24,9,25,6,18,4,3,20
45,2003,18,1148,77,W,0,29,61,6,14,13,17,17,23,12,15,3,2,11
46,2003,18,1150,89,W,0,31,66,11,27,16,27,13,20,16,10,23,4,20
47,2003,18,1151,68,W,0,23,47,4,14,18,26,14,24,13,14,0,4,10
48,2003,18,1157,77,W,0,27,63,3,11,20,23,19,19,13,11,6,1,19
49,2003,18,1158,84,W,0,30,60,9,18,15,22,10,21,14,16,7,1,22

In [10]:
# Combine both tournament and reg season results
all_game_results_df = pd.concat([
        season_results_df[['Season', 'DayNum', 'TeamID', 'Score', 'Outcome', 'NumOT', 'FGM', 'FGA',
       'FGM3', 'FGA3', 'FTM', 'FTA', 'OR', 'DR', 'Ast', 'TO', 'Stl', 'Blk',
       'PF']],
        results_df[['Season', 'DayNum', 'TeamID', 'Score', 'Outcome', 'NumOT', 'FGM', 'FGA',
       'FGM3', 'FGA3', 'FTM', 'FTA', 'OR', 'DR', 'Ast', 'TO', 'Stl', 'Blk',
       'PF']]
])
    
# View resulting df
all_game_results_df.head()

,Season,DayNum,TeamID,Score,Outcome,NumOT,FGM,FGA,FGM3,FGA3,FTM,FTA,OR,DR,Ast,TO,Stl,Blk,PF
0,2003,10,1104,68,W,0,27,58,3,14,11,18,14,24,13,23,7,1,22
1,2003,10,1272,70,W,0,26,62,8,20,10,19,15,28,16,13,4,4,18
2,2003,11,1266,73,W,0,24,58,8,18,17,29,17,26,15,10,5,2,25
3,2003,11,1296,56,W,0,18,38,3,9,17,31,6,19,11,12,14,2,18
4,2003,11,1400,77,W,0,30,61,6,14,11,13,17,22,12,14,4,4,20

In [11]:
# Check the length
len(all_game_results_df)

203208

In [14]:
# Export to csv
all_game_results_df.to_csv('all_game_results.csv')